server:
  port:
    2009

feign:
  hystrix:
    enabled:
     true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            
eureka:
  client:
    registryFetchIntervalSeconds: 5
    
endpoints:
  routes:
    sensitive: false

management:
  security:
    enabled:
      false

foo:
  foo version 125

spring:
  rabbitmq:
    host:
      localhost
    port:
      5672
    username:
      guest
    password:
      guest
    virtual-host:
      /
    publisher-confirms:
      true
